### ISSUE TITLE
Microcontroller support

### ISSUE THREAD

**Issue by Titaniumtown** [nyurik/automotive_diag#13]
Hello! I'm in the preliminary state of planning a project using a stm32 and communicating with my car via the OBD-II port. Does this crate have support for targeting microcontrollers?

**Comment by nyurik** [comment]
Hi, this project is agnostic to the target - it will compile even for `no_std` targets. Think of it as a bunch of glorified `enum` statements with documentation.

**Comment by Titaniumtown** [comment]
Oh ok. I misunderstood the aim of the project. Thank you!

**Comment by nyurik** [comment]
no problem.  The aim is to define "what" gets transmitted/received, not "how" it gets there
