### ISSUE TITLE
VSCode's rust-analyzer extension crashes because of "Multi-lines is disabled by default by displaydoc."

### ISSUE THREAD

**Issue by sirius-ccwu** [nyurik/automotive_diag#8]
This crate's UdsCommand causes crash of VSCode's rust-analyzer extension.

**Comment by nyurik** [comment]
@sirius-ccwu thx for reporting, but this sounds like a bug in the rust-analyzer?  Is there a relevant issue in that project? I would love to help to solve it.

**Comment by sirius-ccwu** [comment]
I don't think is a bug of rust-analyzer. Rus-analyzer does not use displaydoc.

**Comment by sirius-ccwu** [comment]
It's resulted by the comment of UdsCommand::RoutineControl. More detailed error,
`thread '<unnamed>' panicked at 'Multi-line comments are disabled by default by displaydoc. Please consider using block doc comments (/** */) or adding the #[ignore_extra_doc_attributes] attribute to your type next to the derive.', /home/ccwu/.cargo/registry/src/github.com-1ecc6299db9ec823/displaydoc-0.2.4/src/attr.rs:78:13
stack backtrace:
   0: std::panicking::begin_panic
   1: displaydoc::attr::AttrsHelper::display`

**Comment by sirius-ccwu** [comment]
I've fixed it by using a `/** */`, but `test_display_doc` failed.

**Comment by sirius-ccwu** [comment]
I've also opened a bug report on rust-analyzer at https://github.com/rust-lang/rust-analyzer/issues/15840.

**Comment by nyurik** [comment]
@sirius-ccwu I cannot reproduce your issue.  My vscode is v1.84.0 and rust analyzer v0.3.1722

I simply opened the project (dir) with this repository, and tried running and step-by-step debugging of the `spot_test` in `lib.rs`.  I also tried typing code, and viewing most of the UDS module's files - no issues.

<details><summary>version info</summary>

### vscode

```
Version: 1.84.0
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:28:21.782Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-88-generic
```

### rust-analyzer

Name: rust-analyzer
Id: rust-lang.rust-analyzer
Description: Rust language support for Visual Studio Code
Version: 0.3.1722
Publisher: The Rust Programming Language 
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer

</details>

**Comment by sirius-ccwu** [comment]
I'm also using vscode 1.84.0 and rust-analyzer extension 0.3.1722 on WSL. I run code in the automotive_diag, open the Output pane, select output of Rust Analyzer Language Server. A thread handling procedure macro crashes.

**Comment by nyurik** [comment]
I released another version that has only one line per doc. Not ideal but oh well.
